# Generated by Django 2.1.4 on 2018-12-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='altcontactno',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='balance',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='billstatus',
            field=models.BooleanField(default=0, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='cloth_quantity',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='order_status',
            field=models.CharField(default='Pending', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='total_bill',
            field=models.FloatField(editable=False),
        ),
    ]
