# Generated by Django 2.1.4 on 2018-12-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0005_auto_20181227_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderdetails',
            name='text',
            field=models.CharField(default='save', max_length=20),
        ),
    ]
