# Generated by Django 2.1.4 on 2018-12-27 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0006_customerorderdetails_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorderdetails',
            name='text',
        ),
    ]
